### ISSUE TITLE
Letters game missing solutions

### ISSUE THREAD

**Issue by jeirman** [Koallider/8OO10CDC_FLUTTER#16]
Hello,

not sure if you are still maintaining this but I am gonna to take a shot.
First of all, congrats on the easy to understand code. It has helped me a lot in trying to further my coding experience. However I did notice that in the letters game not all solutions are found.

If I use the letters 'GREEDYIER' I get the following results:
RIDGER
DEGREE
DERERE
GIRDER
EERIER
GREYER
REGIRD
DRIER
DIRGE

But the following are missing (more letters used):
GREEDIER
REEDIER
GREEDY

Also if I use letters 'ABSOLUTES', it does find the word 'absolutes' but not 'absolute'.

What could explain this behaviour?

**Comment by Koallider** [comment]
Hi, I'm glad that you found my code helpful

You are right, the algorithm returns incorrect results for the input from your example. 
I did some research and discovered a mistake in a permutation generation. 

I'll try to explain what happened. 
The problem is in findCeil method. If there are multiple instances of the same letter in the array, findCeil returns index of the first letter. For Example for array `[g, r, d, y, r, i, e, e, e]` and fromIndex = 2, ceil index will be 6, because 'e' is the smallest letter which is greater than 'd'.  Then later we swap those letters to get this array `[g, r, e, y, r, i, d, e, e]`. First letter 'e' is replaced by 'd'. Then we reverse the array starting from 'y' to get this `[g, r, e, e, e, d, i, r, y]`. As you can see all 3 instances of letter 'e' are going one after another. And because 'd' is smaller than 'e' we never actually get `[g, r, e, e, d, ... ]` permutation. That's why the words you are expecting are not in the results. 

However. If we make `findCeil` return the last smallest letter which is greater then the letter on `fromIndex` (In this example findCeli should return 8), we will get following array after the swap `[g, r, e, y, r, i, e, e, d]` which will allow us to generate all the following permutations correctly. 

I'll update the code to fix the problem. You can fix it right now by replacing `word[i].compareTo(word[ceilIndex]) < 0` with `'word[i].compareTo(word[ceilIndex]) <= 0` in letter_solver.dart

Thanks for opening this issue. I hope my comment was helpful.

Regarding the 'absolute' and 'absolutes'.  'absolute' is for some reason not in the dictionary but 'absolutes' is.
